# Copyright (c) 2021 JannesM
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.

from base64 import encode
import hashlib
import time
    
class Transaction:
    """Primitive class that describes a transaction
    """
    # header
    timestamp: bytes # (20)
    script_pub_key: bytes # (33)

    # contents
    sender: bytes # (34)
    receiver: bytes # (34)
    asset: bytes # (tByte) -> Tokens: (10) 000.000000 #6 digest | Hash: (32) sha256

    # signature
    hash: bytes # (32)
    script_sig: bytes # (64)

    def __init__(self, pk, sender, receiver, timestamp=None) -> None:
        if timestamp is None:
            self.timestamp = self.allocate(time.time(), 20)

        else:
            self.timestamp = self.allocate(timestamp, 20)
        
        self.script_pub_key = pk
        
        self.sender = sender
        self.receiver = receiver
        self.asset = b'\xa0'

        self.hash = self.calculate_hash()

    def calculate_hash(self) -> bytes:
        buffer = self.timestamp + self.script_pub_key + self.sender + self.receiver + self.asset
        
        return hashlib.sha256(buffer).digest()

    def generate_token_asset(self, token: float) -> bytes:
        self.asset = b'\xa1' + self.allocate(token, 10)
        self.hash = self.calculate_hash()

    def generate_hash_asset(self, hash) -> bytes:
        self.asset = b'\xa2' + hash
        self.hash = self.calculate_hash()
    
    def allocate(self, data, length) -> bytes:
        """Function to allocate length of any data to a specific length

        Args:
            timestamp (float): unix timestamp generated by time.time()

        Returns the encoded string representation with length 20
        """

        data = str(data).encode('utf-8')
        if len(data) < length:
            diff = length - len(data)
            placeholder = ''.join('0' for _ in range(diff)).encode('utf-8')
            return placeholder + data

        return data

    def get_timestamp(self) -> float:
        """Function that converts unix timestamp from bytes to float

        Returns unix timestamp as a floating point number
        """
        return float(self.timestamp.decode())